name: Readme Generator
on:
  schedule: [{cron: '0 0 * * *'}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📊 Left Panel - Profile & Calendar & Stars
        uses: lowlighter/metrics@latest
        with:
          filename: assets/left.svg
          token: ${{ secrets.GH_TOKEN }}
          user: spant671-ux
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, stars
          plugin_isocalendar: yes
          plugin_stars: yes
          plugin_stars_limit: 3

      - name: 📊 Right Panel - Languages
        uses: lowlighter/metrics@latest
        with:
          filename: assets/right.svg
          token: ${{ secrets.GH_TOKEN }}
          user: spant671-ux
          base: ""
          config_order: languages
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
